server:
  port: 8002
  
spring:
  application:
    name: auth-service
  data:
    mongodb:
      host: localhost
      port: 27017
      user: toby
      authentication-database: admin
      database: engapp
      password: ZAQ!2wsx
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka