spring:
  application:
    name: db-service
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: engapp
      username: toby
      password: ZAQ!2wsx
      
server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
      
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: engapp-client
      client-secret: engapp-secret
      access-token-uri: http://localhost:8002/oauth/token
      user-authorization-uri: http://localhost:8002/oauth/authorize
    resource:
      user-info-uri: http://localhost:8002/api/user/account